### ISSUE TITLE
Support for 5.7" 

### ISSUE THREAD

**Issue by brainlessboy** [aeroniemi/inky-ts#1]
Hi :-) will you provide support for other Inky sizes? e.g. 4" and 5.7" ?

**Comment by aeroniemi** [comment]
I've added a UC8159 driver (used by the Impression 4 and 5.7) to the repository and built it as a package:

https://github.com/aeroniemi/inky-ts/pkgs/npm/inky

It hasn't been tested as I don't have any of those devices to try it out on, so if you find any issues let me know.

**Comment by brainlessboy** [comment]
many many thanks!, i am trying to get this running (on a raspi zero 2w, itested the hardware setup with python) ... the javascript code looks like this (used your example code):
```
import { InkyImpression57 } from "@aeroniemi/inky"

async function main() {
    let screen = new Impression57()
    screen.display_png("./bubblerobot.png")
    await screen.show()
}
main()
```

but i get this error:

```
import { InkyImpression57 } from "@aeroniemi/inky"
         ^^^^^^^^^^^^^^^^
SyntaxError: Named export 'InkyImpression57' not found. The requested module '@aeroniemi/inky' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@aeroniemi/inky';
const { InkyImpression57 } = pkg;
```

i tried that other way but then i still get an error because its not finding any InkyImpression57 to intanciate ...

this is what my package json looks like for the test ...
```
{
  "name": "screentest",
  "version": "1.0.0",
  "description": "epaper javascript test",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "bubblerobot",
  "license": "ISC",
  "dependencies": {
    "@aeroniemi/inky": "^0.1.2",
    "@resvg/resvg-js": "^2.6.0",
    "rpio": "^2.4.2"
  }
}
```

**Comment by aeroniemi** [comment]
That's great to hear - I'll merge the relevant PR and close the duplicate alongside the changes to the readme!

I now remember that I didn't actually write the code related to defining ``this.resolution_setting`` , so that's probably the cause of the issue related to that (it thinking that you're on a 4" display)

**Comment by brainlessboy** [comment]
many thanks will close this then :-)
