### ISSUE TITLE
Partial Screen Update

### ISSUE THREAD

**Issue by brainlessboy** [aeroniemi/inky-ts#6]
Hi, would it be possible to add partial screen update?
e.g. a function partialUpdate(buf,sx,sz,sw,sh ) which only updates that specific square region.

i did some research and found this:
(the links dont work any more, i wonder if there are specs somewhere)
The mono version at https://www.china-epaper.com/uploads/soft/DEPG0420A01V3.0.pdf suggests that SPI command 0x22 0xC0 will do a partial update in Section 13.4 even though it doesn't show it as supported in the command table. The multicolour manual at https://www.china-epaper.com/uploads/soft/DEPG0420R01V3.0.pdf doesn't even suggest it although it does still support the partial ram address commands 0x44, 0x45, 0x4e, 0x4f as well so it would probably work, possibly badly for the reasons Gadgetoid mentioned. (gagetoid mentioned the borders would be seen due to some blur/antialiasing) but i would not bother about this...

**Comment by aeroniemi** [comment]
I'd love to add this, but we'd need to work out how to get the screen to respond to it.

The AC073TC1 used by the 7.3" doesn't appear to support partial update at all (although it's slightly hard to tell without a complete datasheet), although the UC8159 might.

**Comment by aeroniemi** [comment]
This suggests that the UC8159 chip doesn't support it, so you're probably out of luck:
https://github.com/pimoroni/inky/issues/122#issuecomment-1125143130

**Comment by brainlessboy** [comment]
thanks, yeah got the same response from every where, that screen is super cool but to slow, never the less, all things you added are still super useful!, thanks allot.
